### ISSUE TITLE
markdown bullet point not showing 

### ISSUE THREAD

**Issue by kyungyunlee** [milooy/TIL#11]
유림님 안녕하세요!
좋은 템플릿 감사합니다 :)
markdown안에서 bullet point (* ,  -)를 사용하면 그게 렌더링해서 안보여지는데 이건 어떤 문제일까요? 
참고로 저는 크롬으로 보고 있습니다.

감사합니다!

**Comment by milooy** [comment]
안녕하세요 ㅎㅎ 
전역 css파일에서 
```
ul {
    list-style: inherit !important;
}
```
를 넣어주면 되실 것 같습니다.
현재 기본 테마에는 none으로 되어있네요 ㅎㅎ

저도 보는게 불편해서 추후에 업뎃 할 예정이에요!

![image](https://user-images.githubusercontent.com/3839771/109804770-fa6e3600-7c65-11eb-8aba-e12c280575b0.png)

**Comment by kyungyunlee** [comment]
정말 감사합니다 유림님! :)
